# Generated by Django 4.2.11 on 2024-05-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
    ]
